<a href="https://colab.research.google.com/github/HAgarOsman2002/Deep-learning-projects/blob/main/tensorflow_version1_impmentation_%26_linear_regression_from_scratch_using_V1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**import libraries**


In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib as plt
import seaborn as sns
import pandas as pd

 * disable tensorflow version 2 to work with vesrion 1

In [ ]:
tf.compat.v1.disable_eager_execution()

* data Types on tensorflow 1 are constatns and variables but u have to convert them to tensors
  
#step 1 Graph (definition):
       * we just applied the definition to create the graph so when we printed the x the value of it doesn't appear instead of this
        (x= tf.constant('Tensorflow'))


In [ ]:
x= tf.constant('Tensorflow')
print(x)

Tensor("Const:0", shape=(), dtype=string)


#**step 2 Excution (open session)**

In [ ]:
sess = tf.compat.v1.Session()
s = sess.run(x)
print(s)
sess.close()    #(b) for object

b'Tensorflow'


another trial

In [ ]:
x =tf.constant(4)
y = tf.constant(10)
z= tf.add(x,y)
print(z)

Tensor("Add:0", shape=(), dtype=int32)


In [ ]:
sess = tf.compat.v1.Session()
s = sess.run(z)
print(s)
sess.close()    #(b) for object

14


another way to close the session

In [ ]:
with tf.compat.v1.Session() as sess:
  res=sess.run(z)
  print(res)

14


In [ ]:
#Defining numby matrix
var1 = np.arange(1,13,dtype=np.int32) #12
var2 = np.arange(15,27,dtype=np.int32) #12 digit of range 15:17
var1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [ ]:
#converting matrces to tensors
mat1=tf.constant(var1,shape=[3,4])
mat2=tf.constant(var1,shape=[4,3])
res = tf.matmul(mat1,mat2)
res

<tf.Tensor 'MatMul:0' shape=(3, 3) dtype=int32>

In [ ]:
#open & clossing session to print results
with tf.compat.v1.Session() as sess:
  res=sess.run(res)
  print(res)

[[ 70  80  90]
 [158 184 210]
 [246 288 330]]


#Exercice:
   * get the :v1=[1,2,3,4] ,v2[6,7,8,9]
    * add
    * sub
    * multi
    * divide


In [ ]:
#converting matrces to tensors
v1 = tf.constant([1,2,3,4])
v2 = tf.constant([6,7,8,9])

mult = tf.multiply(v1,v2)
add = tf.add(v1,v2)
subtract = tf.subtract(v1,v2)
divide = tf.divide(v1,v2)

with tf.compat.v1.Session() as sess:
  print(sess.run(mult))
  print(sess.run(add))
  print(sess.run(subtract))
  print(sess.run(divide))



[ 6 14 24 36]
[ 7  9 11 13]
[-5 -5 -5 -5]
[0.16666667 0.28571429 0.375      0.44444444]


#**apply linear regression using Tensorflow**
    * y = wx + b

In [ ]:
X_data =np.random.randn(4,9)  #randn btgeb arkam random bs feha normal distribution
w_data =np.random.randn(9,1)
b_data =np.zeros(4)

In [ ]:
x = tf.constant(X_data, shape = [4,9])
w = tf.constant(w_data, shape = [9,1])  # weight should not be constat
b = tf.constant(b_data, shape = [4,1])

In [ ]:
y = tf.add(tf.matmul(x,w),b)

In [ ]:
with tf.compat.v1.Session() as sess:
  print(sess.run(y))

[[-3.42153403]
 [-0.7674388 ]
 [ 3.34128307]
 [ 1.37241712]]


#variable
   * to make varibale u have to

     1.   definition
     2.   initialization
     3.   Excution(session)



In [ ]:
var1 = tf.Variable(12 , name="variable")
var2 = tf.Variable(13 , name="variable")

In [ ]:
init = tf.compat.v1.global_variables_initializer()

In [ ]:
with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(var1))

12


#**linear regression using variable**
 * w = [[1,2,3]]
 * x = [3] ,[4] ,[5]
 * b=1

In [ ]:
from operator import matmul
x = tf.constant([[3],[4],[4]],shape=(3,1))
w = tf.Variable([[1,2,3]],shape=(1,3))
b = tf.Variable(1)
res = tf.add(tf.matmul(x,w),b)
res

<tf.Tensor 'Add_4:0' shape=(3, 3) dtype=int32>

In [ ]:
init = tf.compat.v1.global_variables_initializer()

In [ ]:
with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(res))

[[ 4  7 10]
 [ 5  9 13]
 [ 5  9 13]]


#**Linear Regression using Gradient descent to update the weight**

In [ ]:
x_data = np.array([ [4,2],[3,5],[4,5],[4,3] ],dtype=f"float64")
y_data = np.array([ [5],[7],[6],[9] ],dtype=f"float64")

In [ ]:
x = tf.constant(x_data)
y =  tf.constant(y_data)

w = tf.Variable(np.random.randn(2,1))
b = tf.Variable(np.zeros(4),dtype="float32")

In [ ]:
init = tf.compat.v1.global_variables_initializer()

In [ ]:
#feedforward
y_pred = tf.add(tf.matmul(x,w),b)
#Backrward
cost =1/n * tf.square(y_pred -y)

TypeError: Input 'y' of 'AddV2' Op has type float32 that does not match type float64 of argument 'x'.